### ISSUE TITLE
Release 0.0.1 on PyPI

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-animation#28]
Before releasing I'd like us to

- [ ] Close #29 by adding more comprehensive tests
- [x] Close #16 and drop the skimage dependency
- [x] Close #11 which will require napari 0.4.5 (including https://github.com/napari/napari/pull/2042)
- [ ] Close #9 and improve the readme

As we get close to the release I'll also move this over to live at `napari/napari-animation` instead of my personal account, but I want it to get a little bit further along before then.

cc @alisterburt

**Comment by alisterburt** [comment]
Looks great, will work through the list this week!

**Comment by alisterburt** [comment]
Haven't added specific tests on what type of data is coming for each property from the viewer but playing with the latest napari everything seems to be working smoothly, closing #11 (might need to up the minimum napari version?)

There's been progress towards #29 in #34 - can definitely be further improved

#9 is at least partially addressed by #32, I might add a sentence about adding the dock widget from the plugin menu too though

**Comment by sofroniewn** [comment]
Ok nice, sounds like we're making good progress here, would be great to here from @guiwitz other things we want to see before our first release!

**Comment by guiwitz** [comment]
It wasn't really on the list, but I made an attempt #43 at fixing the interactive saving which was non-functional in several aspects. I think this is essential before release. Let me know what you think of the current solution. It's pretty much just fixes to make it work as it was supposed to (I think).

**Comment by sofroniewn** [comment]
Any further thoughts on this @alisterburt @guiwitz? I think we're in a good place to release. Maybe we do some final checks and then try to get `0.0.1` out next week? We can still keep working on it to make it better too :-)

**Comment by alisterburt** [comment]
Just updated #40 - I think it would be worth getting that in for 0.0.1 so people can show/hide layers during an animation, otherwise I think we're good to go! 🚀

**Comment by guiwitz** [comment]
I just pushed a PR #45 that I had planned to submit earlier that adds a scroller to smoothly move through the animation. If you have time to review, it would be nice to have in the first release, but we can also work on that later.

**Comment by sofroniewn** [comment]
Nice! Let's try and get both #40 and #45 in for our `0.0.1`. I'll get to some reviews soon

**Comment by sofroniewn** [comment]
Ok I think we're all done and ready to go for `0.0.1`. I can try and make a release candidate that we can test and then we can release!!

**Comment by sofroniewn** [comment]
I'm just running into some problems with the pypi credentials and deploy step, but as soon as i get them sorted out i'll get the first rc uploaded!! thanks for everyones patience! (cc @jni @tlambert03 we might want to overhaul our secrets at the org level to make it easier for new repos like this one!)

**Comment by alisterburt** [comment]
excellent stuff - thanks for the update, looking forward to it!

**Comment by sofroniewn** [comment]
Ok, looks like `0.0.1rc2` has made it on to PyPI, see https://pypi.org/project/napari-animation/.

It should be possible to install as `pip install --pre napari-animation`

I've tested in a clean environment and it works for me! Maybe @alisterburt you can test too and then we can release?

I think we should also put together a tweet series to announce the package next week, if either of you have any cool movies to share. We can discuss more in zulip too

**Comment by alisterburt** [comment]
awesome thanks @sofroniewn !! exciting

installing into a fresh environment works great for me too - I'm running into save dialog issues when running in ipython (napari/napari#2571) but running napari from the shell this is working fine too.

The functionality we have appears to be working well, I've noticed a few small problems - I'll open individual issues for them but I don't think they're blocking, 0.0.2 will be even better!

Re: the tweet series, I'll remake [my little virus animation](https://twitter.com/AlisterBurt/status/1356631458941698048) and screen record the process over the weekend so we have some video of the interactivity. Excited to see what others might like to show? @guiwitz

**Comment by guiwitz** [comment]
I just installed in a fresh conda environment and everything went smoothly. I'm not running into any problem with the save dialog on my Mac (still under 10.15, so maybe that explains this). One thing doesn't seem to work: the Readme says that ```Layer.visible``` should animatable. However when I create a movie and turn a given layer off, it turns it off for the entire movie. Is the Readme wrong or is this a bug (or I'm using this in the wrong way)?

**Comment by alisterburt** [comment]
@guiwitz I just checked locally and can't reproduce the error, my `keyframe['viewer']['layers']' dicts contain the `visible` property and interpolation works as expected for boolean values

Are opacity changes working fine for you? Which version of napari are you running against?

```
napari: 0.4.7
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - animation: 0.1.dev127+ge563f6a.d20210416

```

**Comment by alisterburt** [comment]
trying to remake the virus animation now and *something* is causing `Animation.set_to_keyframe()` to take a long time... investigating

**Comment by guiwitz** [comment]
> @guiwitz I just checked locally and can't reproduce the error, my `keyframe['viewer']['layers']` dicts contain the `visible` property and interpolation works as expected for boolean values
> 
> Are opacity changes working fine for you? Which version of napari are you running against?

Sorry, everything works fine. Rookie mistake, I was running my notebook in the (apparently not up-to-date) napari-animation repo which was overriding the fresh pip installation.

**Comment by sofroniewn** [comment]
Hi all, I've now pushed `v0.0.1rc5`. It should be ready for testing!!

**Comment by sofroniewn** [comment]
`0.0.1` is now live!! Thanks all https://pypi.org/project/napari-animation/
